import type { Config } from "tailwindcss";

export default {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/shared/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    screens: {
      xs: "350px",
      sm: "500px",
      md: "768px",
      lg: "1024px",
      xl: "1280px",
      "2xl": "1440px",
    },
    extend: {
      colors: {
        accentText: "#7e7e7e",
        accentText50: "#8d96a450",
        accentTextDark: "#848e9c",
        accentTextDark50: "#848e9c50",
        constantDark: "#0d0e0f",
        constantLight: "#ffffff",
        bannerBackground: "#101827",
        bannerBackgroundDark: "#08243A",
        border: "#f4f5f7",
        borderDark: "#353335",
        mainBackground: "#f3f3f3",
        mainBackgroundDark: "#010002",
        secondBackground: "#eaeaea",
        secondBackgroundDark: "#080808",
        secondBackgroundDarkTest: "#1a1a1a",
        mainBrand: "#1570EF",
        mainBrandDisable: "#00706e",
        mainBrandAlternative: "#0d77e7",
        mainText: "#252525",
        mainTextDark: "#ffffff",
        negative: "#b71c1c",
        negative50: "#dd0808",
        negativeDark: "#b71c1c",
        darkRed: "#940505",
        surface: "#e0e0e0",
        surfaceDark: "#141414",
        positive50: "#429445",
        positive: "#2e7d32",
        positiveDark: "#2e7d32",
        buttonPositive: "#2e7d32",
        buttonPositiveDark: "#2e7d32",
        gold: "#efbf04",
        backdrop: "#21262F",
        landingMainBackground: "#ffffff",
        landingMainBackgroundDark: "#ffffff",
        landingSecondaryBackground: "#0C111D",
        landingSecondaryBackgroundDark: "#0C111D",
        landingSecondarySurface: "#141C2F",
        landingSecondarySurfaceDark: "#141C2F",
        landingAccentText: "#98A2B3",
        landingAccentTextDark: "#98A2B3",
        landingMainText: "#ffffff",
        landingMainTextDark: "#ffffff",
        landingSecondaryText: "#0C111D",
        landingSecondaryTextDark: "#0C111D",
        landingMainBrand: "#1570EF",
        landingMainBrandDark: "#1570EF",
        ownerChatBackground: "#437057",
        userChatBackground: "#1B3C53",
        badgeBackgroundGreen: "#EDFFED",
        panelDark: "#212121",
        paleBackgroundBlue: "#F3F5FF",
        paleBorderBlue: "#1F73B7",
        panelLight: "#E5E5E5",
        selectionBackground: "#E2E8FF",

        //new colors:
        newColor_textNeutral40: "#808080",
        newColor_textNeutral40Dark: "#6D7077",

        newColor_textNeutral100: "#0A0B0D",
        newColor_borderNeutral10: "#E2E2E3",
        newColor_borderNeutral10Dark: "#22252A",
        newColor_textPrimary50: "#3E71CF",
        newColor_bgPrimary50: "#000000",
        newColor_bgSuccess50: "#2E7D32",
        newColor_bgOrange20: "#FF6838",
        newColor_textError50: "#CF202F",
        newColor_bgNeutral5: "#F8F8F9",
        newColor_bgNeutral5Dark: "#181B1F",
        newColor_bgNavy100Bg: "#070913",
        newColor_borderSolid: "#595959",
        newColor_bgGraySolid: "#262626",
        newColor_bgNavy100: "#070913",
        newColor_bgNavy100Dark: "#343434",
        newColor_bgNeutralWhiteDark: "#0D0F12",
        newColor_bgNeutral15: "#CED2DB",
        newColor_bgNeutral15Dark: "#2D3036",
        newColor_bgNeutral: "#FBFBFC",
        newColor_bgNeutralDark: "#121418",

        textPrimary: "var(--Neutral-100)",
        textSecondary: "var(--Neutral-60)",
        textDisabled: "var(--Neutral-30)",
        textInverse: "var(--Neutral-White)",
        textSolidWhite: "var(--Neutral-Solid)",
        textLink: "var(--Primary-50)",
        textAccent: "var(--Primary-40)",
        textOnAccent: "var(--Neutral-White)",
        textError: "var(--Error-50)",
        textSuccess: "var(--Success-50)",
        textWarning: "var(--Warning-50)",
        textPlaceholder: "var(--Neutral-30)",

        bgDefault: "var(--Neutral-Bg)",
        bgSubtle: "var(--Neutral-5)",
        bgMuted: "var(--Neutral-7)",
        bgSurface: "var(--Neutral-White)",
        bgAccent: "var(--Primary-50)",
        bgInverse: "var(--Navy-100-BG)",
        bgHover: "var(--Primary-40)",
        bgPressed: "var(--Primary-60)",
        bgDisabled: "var(--Neutral-10)",
        bgError: "var(--Error-20)",
        bgSuccess: "var(--Success-20)",
        bgWarning: "var(--Warning-20)",

        borderDefault: "var(--Neutral-10)",
        borderMuted: "var(--Neutral-5)",
        borderFocus: "var(--Navy-20)",
        borderError: "var(--Error-50)",
        borderSuccess: "var(--Success-50)",
        borderWarning: "var(--Warning-50)",
        borderDivider: "var(--Neutral-100)",
        borderSecondary: "var(--Primary-40)",

        iconDefault: "var(--Navy-90)",
        iconMuted: "var(--Neutral-50)",
        iconOnAccent: "var(--Neutral-White)",
        iconError: "var(--Error-50)",
        iconSuccess: "var(--Success-50)",
        iconDisabled: "var(--Neutral-30)",
        iconDivider: "var(--Neutral-100)",
        iconSolidWhite: "var(--White-Solid)",

        stateHover: "var(--Primary-40)",
        stateActive: "var(--Navy-60)",
        stateFocus: "var(--Navy-30)",
        stateDisabled: "var(--Neutral-15)",
        stateSelected: "var(--Navy-50)",

        semanticSuccess: "var(--Success-50)",
        semanticError: "var(--Error-50)",
        semanticWarning: "var(--Warning-50)",
        semanticInfo: "var(--Info-50)",

        overlayDefault: "var(--Neutral-White)",
        elevation1: "var(--Neutral-100)",
        elevation2: "var(--Neutral-100)",

        brandPrimary: "var(--Primary-50)",
        brandSecondary: "var(--Navy-50)",
        brandAccent: "var(--Primary-60)",
        brandOnPrimary: "var(--Neutral-White)",
      },

      backgroundImage: {
        "green-gradient":
          "linear-gradient(0deg, rgba(76, 175, 80, 1) 0%, rgba(36, 79, 36, 1) 75%)",
        "red-gradient":
          "linear-gradient(0deg,rgba(255, 0, 0, 1) 0%, rgba(69, 0, 0, 1) 85%);",
        "landing-text-gradient":
          "linear-gradient(0deg,rgba(189, 189, 189, 1) 25%, rgba(255, 255, 255, 1) 75%);",
        "pattern-lines": "url('/assets/images/card-line-Pattern.svg')",
        "trust-section-line-pattern":
          "url('/assets/images/trust-section-line-pattern.svg')",
        "trust-box-line-pattern":
          "url('/assets/images/trust-box-line-pattern.svg')",

        "line-pattern-light": "url('/assets/images/line-pattern-light.svg')",
        "line-pattern-dark": "url('/assets/images/line-pattern-dark.svg')",
      },
      fontFamily: {
        english: ["enFont", "sans-serif"],
        farsi: ["faFont", "sans-serif"],
      },
      keyframes: {
        scroll: {
          "0%": { transform: "translateX(0%)" },
          "100%": { transform: "translateX(50%)" }, // or -50% for RTL
        },
        reversScroll: {
          "0%": { transform: "translateX(0%)" },
          "100%": { transform: "translateX(-100%)" }, // or -50% for RTL
        },
        fadeUp30: {
          "0%": { opacity: "0", transform: "translateY(30px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        fadeUp50: {
          "0%": { opacity: "0", transform: "translateY(50px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        fadeUp100: {
          "0%": { opacity: "0", transform: "translateY(100px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        fadeIn: {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
        revealClip: {
          "0%": {
            clipPath: "polygon(0% 0%, 0% 0%, 0% 100%, 0% 100%)",
          },
          "50%": {
            clipPath: "polygon(100% 0, 0% 0, 0% 100%, 100% 100%)",
          },
          "100%": {
            clipPath: "polygon(100% 0, 0% 0, 0% 100%, 100% 100%)",
          },
        },
      },
      animation: {
        scroll: "scroll 200s linear infinite",
        reversScroll: "reversScroll 30s linear infinite",
        fadeUp30: "fadeUp30 0.6s ease-out forwards",
        fadeUp50: "fadeUp50 0.6s ease-out forwards",
        fadeUp100: "fadeUp100 0.6s ease-out forwards",
        revealClip: "revealClip 7s ease-in-out forwards",
        fadeIn: "fadeIn 1s ease",
      },
    },
  },
  plugins: [],
  darkMode: "selector",
} satisfies Config;
