export const countries = [
  {
    name_en: "Afghanistan",
    name_fa: "افغانستان",
    name_ru: "Афганистан",
    name_tr: "Afganistan",
    name_ar: "أفغانستان",
    code: "AF",
  },
  {
    name_en: "Albania",
    name_fa: "آلبانی",
    name_ru: "Албания",
    name_tr: "Arnavutluk",
    name_ar: "ألبانيا",
    code: "AL",
  },
  {
    name_en: "Algeria",
    name_fa: "الجزایر",
    name_ru: "Алжир",
    name_tr: "Cezayir",
    name_ar: "الجزائر",
    code: "DZ",
  },
  {
    name_en: "Andorra",
    name_fa: "آندورا",
    name_ru: "Андорра",
    name_tr: "Andorra",
    name_ar: "أندورا",
    code: "AD",
  },
  {
    name_en: "Angola",
    name_fa: "آنگولا",
    name_ru: "Ангола",
    name_tr: "Angola",
    name_ar: "أنغولا",
    code: "AO",
  },
  {
    name_en: "Antigua and Barbuda",
    name_fa: "آنتیگوا و باربودا",
    name_ru: "Антигуа и Барбуда",
    name_tr: "Antigua ve Barbuda",
    name_ar: "أنتيغوا وباربودا",
    code: "AG",
  },
  {
    name_en: "Argentina",
    name_fa: "آرژانتین",
    name_ru: "Аргентина",
    name_tr: "Arjantin",
    name_ar: "الأرجنتين",
    code: "AR",
  },
  {
    name_en: "Armenia",
    name_fa: "ارمنستان",
    name_ru: "Армения",
    name_tr: "Ermenistan",
    name_ar: "أرمينيا",
    code: "AM",
  },
  {
    name_en: "Australia",
    name_fa: "استرالیا",
    name_ru: "Австралия",
    name_tr: "Avustralya",
    name_ar: "أستراليا",
    code: "AU",
  },
  {
    name_en: "Austria",
    name_fa: "اتریش",
    name_ru: "Австрия",
    name_tr: "Avusturya",
    name_ar: "النمسا",
    code: "AT",
  },
  {
    name_en: "Azerbaijan",
    name_fa: "آذربایجان",
    name_ru: "Азербайджан",
    name_tr: "Azerbaycan",
    name_ar: "أذربيجان",
    code: "AZ",
  },
  {
    name_en: "Bahamas",
    name_fa: "باهاما",
    name_ru: "Багамские Острова",
    name_tr: "Bahamalar",
    name_ar: "جزر البهاما",
    code: "BS",
  },
  {
    name_en: "Bahrain",
    name_fa: "بحرین",
    name_ru: "Бахрейн",
    name_tr: "Bahreyn",
    name_ar: "البحرين",
    code: "BH",
  },
  {
    name_en: "Bangladesh",
    name_fa: "بنگلادش",
    name_ru: "Бангладеш",
    name_tr: "Bangladeş",
    name_ar: "بنغلاديش",
    code: "BD",
  },
  {
    name_en: "Barbados",
    name_fa: "باربادوس",
    name_ru: "Барбадос",
    name_tr: "Barbados",
    name_ar: "بربادوس",
    code: "BB",
  },
  {
    name_en: "Belarus",
    name_fa: "بلاروس",
    name_ru: "Беларусь",
    name_tr: "Belarus",
    name_ar: "بيلاروسيا",
    code: "BY",
  },
  {
    name_en: "Belgium",
    name_fa: "بلژیک",
    name_ru: "Бельгия",
    name_tr: "Belçika",
    name_ar: "بلجيكا",
    code: "BE",
  },
  {
    name_en: "Belize",
    name_fa: "بلیز",
    name_ru: "Белиз",
    name_tr: "Belize",
    name_ar: "بليز",
    code: "BZ",
  },
  {
    name_en: "Benin",
    name_fa: "بنین",
    name_ru: "Бенин",
    name_tr: "Benin",
    name_ar: "بنين",
    code: "BJ",
  },
  {
    name_en: "Bhutan",
    name_fa: "بوتان",
    name_ru: "Бутан",
    name_tr: "Butan",
    name_ar: "بوتان",
    code: "BT",
  },
  {
    name_en: "Bolivia",
    name_fa: "بولیوی",
    name_ru: "Боливия",
    name_tr: "Bolivya",
    name_ar: "بوليفيا",
    code: "BO",
  },
  {
    name_en: "Bosnia and Herzegovina",
    name_fa: "بوسنی و هرزگوین",
    name_ru: "Босния и Герцеговина",
    name_tr: "Bosna-Hersek",
    name_ar: "البوسنة والهرسك",
    code: "BA",
  },
  {
    name_en: "Botswana",
    name_fa: "بوتسوانا",
    name_ru: "Ботсвана",
    name_tr: "Botsvana",
    name_ar: "بوتسوانا",
    code: "BW",
  },
  {
    name_en: "Brazil",
    name_fa: "برزیل",
    name_ru: "Бразилия",
    name_tr: "Brezilya",
    name_ar: "البرازيل",
    code: "BR",
  },
  {
    name_en: "Brunei",
    name_fa: "برونئی",
    name_ru: "Бруней",
    name_tr: "Brunei",
    name_ar: "بروناي",
    code: "BN",
  },
  {
    name_en: "Bulgaria",
    name_fa: "بلغارستان",
    name_ru: "Болгария",
    name_tr: "Bulgaristan",
    name_ar: "بلغاريا",
    code: "BG",
  },
  {
    name_en: "Burkina Faso",
    name_fa: "بورکینافاسو",
    name_ru: "Буркина-Фасо",
    name_tr: "Burkina Faso",
    name_ar: "بوركينا فاسو",
    code: "BF",
  },
  {
    name_en: "Burundi",
    name_fa: "بوروندی",
    name_ru: "Бурунди",
    name_tr: "Burundi",
    name_ar: "بوروندي",
    code: "BI",
  },
  {
    name_en: "Cabo Verde",
    name_fa: "کیپ ورد",
    name_ru: "Кабо-Верде",
    name_tr: "Yeşil Burun Adaları",
    name_ar: "الرأس الأخضر",
    code: "CV",
  },
  {
    name_en: "Cambodia",
    name_fa: "کامبوج",
    name_ru: "Камбоджа",
    name_tr: "Kamboçya",
    name_ar: "كمبوديا",
    code: "KH",
  },
  {
    name_en: "Cameroon",
    name_fa: "کامرون",
    name_ru: "Камерун",
    name_tr: "Kamerun",
    name_ar: "الكاميرون",
    code: "CM",
  },
  {
    name_en: "Canada",
    name_fa: "کانادا",
    name_ru: "Канада",
    name_tr: "Kanada",
    name_ar: "كندا",
    code: "CA",
  },
  {
    name_en: "Central African Republic",
    name_fa: "جمهوری آفریقای مرکزی",
    name_ru: "Центральноафриканская Республика",
    name_tr: "Orta Afrika Cumhuriyeti",
    name_ar: "جمهورية أفريقيا الوسطى",
    code: "CF",
  },
  {
    name_en: "Chad",
    name_fa: "چاد",
    name_ru: "Чад",
    name_tr: "Çad",
    name_ar: "تشاد",
    code: "TD",
  },
  {
    name_en: "Chile",
    name_fa: "شیلی",
    name_ru: "Чили",
    name_tr: "Şili",
    name_ar: "تشيلي",
    code: "CL",
  },
  {
    name_en: "China",
    name_fa: "چین",
    name_ru: "Китай",
    name_tr: "Çin",
    name_ar: "الصين",
    code: "CN",
  },
  {
    name_en: "Colombia",
    name_fa: "کلمبیا",
    name_ru: "Колумбия",
    name_tr: "Kolombiya",
    name_ar: "كولومبيا",
    code: "CO",
  },
  {
    name_en: "Comoros",
    name_fa: "کومور",
    name_ru: "Коморы",
    name_tr: "Komorlar",
    name_ar: "جزر القمر",
    code: "KM",
  },
  {
    name_en: "Congo (Congo-Brazzaville)",
    name_fa: "کنگو (کنگو-برازاویل)",
    name_ru: "Конго (Конго-Браззавиль)",
    name_tr: "Kongo (Kongo-Brazzaville)",
    name_ar: "الكونغو (الكونغو برازافيل)",
    code: "CG",
  },
  {
    name_en: "Costa Rica",
    name_fa: "کاستاریکا",
    name_ru: "Коста-Рика",
    name_tr: "Kosta Rika",
    name_ar: "كوستاريكا",
    code: "CR",
  },
  {
    name_en: "Croatia",
    name_fa: "کرواسی",
    name_ru: "Хорватия",
    name_tr: "Hırvatistan",
    name_ar: "كرواتيا",
    code: "HR",
  },
  {
    name_en: "Cuba",
    name_fa: "کوبا",
    name_ru: "Куба",
    name_tr: "Küba",
    name_ar: "كوبا",
    code: "CU",
  },
  {
    name_en: "Cyprus",
    name_fa: "قبرس",
    name_ru: "Кипр",
    name_tr: "Kıbrıs",
    name_ar: "قبرص",
    code: "CY",
  },
  {
    name_en: "Czech Republic",
    name_fa: "جمهوری چک",
    name_ru: "Чешская Республика",
    name_tr: "Çek Cumhuriyeti",
    name_ar: "جمهورية التشيك",
    code: "CZ",
  },
  {
    name_en: "Denmark",
    name_fa: "دانمارک",
    name_ru: "Дания",
    name_tr: "Danimarka",
    name_ar: "الدنمارك",
    code: "DK",
  },
  {
    name_en: "Djibouti",
    name_fa: "جیبوتی",
    name_ru: "Джибути",
    name_tr: "Cibuti",
    name_ar: "جيبوتي",
    code: "DJ",
  },
  {
    name_en: "Dominica",
    name_fa: "دومینیکا",
    name_ru: "Доминика",
    name_tr: "Dominika",
    name_ar: "دومينيكا",
    code: "DM",
  },
  {
    name_en: "Dominican Republic",
    name_fa: "جمهوری دومینیکن",
    name_ru: "Доминиканская Республика",
    name_tr: "Dominik Cumhuriyeti",
    name_ar: "جمهورية الدومينيكان",
    code: "DO",
  },
  {
    name_en: "Ecuador",
    name_fa: "اکوادور",
    name_ru: "Эквадор",
    name_tr: "Ekvador",
    name_ar: "الإكوادور",
    code: "EC",
  },
  {
    name_en: "Egypt",
    name_fa: "مصر",
    name_ru: "Египет",
    name_tr: "Mısır",
    name_ar: "مصر",
    code: "EG",
  },
  {
    name_en: "El Salvador",
    name_fa: "السالوادور",
    name_ru: "Сальвадор",
    name_tr: "El Salvador",
    name_ar: "السلفادور",
    code: "SV",
  },
  {
    name_en: "Equatorial Guinea",
    name_fa: "گینه استوایی",
    name_ru: "Экваториальная Гвинея",
    name_tr: "Ekvator Ginesi",
    name_ar: "غينيا الاستوائية",
    code: "GQ",
  },
  {
    name_en: "Eritrea",
    name_fa: "اریتره",
    name_ru: "Эритрея",
    name_tr: "Eritre",
    name_ar: "إريتريا",
    code: "ER",
  },
  {
    name_en: "Estonia",
    name_fa: "استونی",
    name_ru: "Эстония",
    name_tr: "Estonya",
    name_ar: "إستونيا",
    code: "EE",
  },
  {
    name_en: "Eswatini",
    name_fa: "اسواتینی",
    name_ru: "Эсватини",
    name_tr: "Esvatini",
    name_ar: "إسواتيني",
    code: "SZ",
  },
  {
    name_en: "Ethiopia",
    name_fa: "اتیوپی",
    name_ru: "Эфиопия",
    name_tr: "Etiyopya",
    name_ar: "إثيوبيا",
    code: "ET",
  },
  {
    name_en: "Fiji",
    name_fa: "فیجی",
    name_ru: "Фиджи",
    name_tr: "Fiji",
    name_ar: "فيجي",
    code: "FJ",
  },
  {
    name_en: "Finland",
    name_fa: "فنلاند",
    name_ru: "Финляндия",
    name_tr: "Finlandiya",
    name_ar: "فنلندا",
    code: "FI",
  },
  {
    name_en: "France",
    name_fa: "فرانسه",
    name_ru: "Франция",
    name_tr: "Fransa",
    name_ar: "فرنسا",
    code: "FR",
  },
  {
    name_en: "Gabon",
    name_fa: "گابن",
    name_ru: "Габон",
    name_tr: "Gabon",
    name_ar: "الغابون",
    code: "GA",
  },
  {
    name_en: "Gambia",
    name_fa: "گامبیا",
    name_ru: "Гамбия",
    name_tr: "Gambiya",
    name_ar: "غامبيا",
    code: "GM",
  },
  {
    name_en: "Georgia",
    name_fa: "گرجستان",
    name_ru: "Грузия",
    name_tr: "Gürcistan",
    name_ar: "جورجيا",
    code: "GE",
  },
  {
    name_en: "Germany",
    name_fa: "آلمان",
    name_ru: "Германия",
    name_tr: "Almanya",
    name_ar: "ألمانيا",
    code: "DE",
  },
  {
    name_en: "Ghana",
    name_fa: "غنا",
    name_ru: "Гана",
    name_tr: "Gana",
    name_ar: "غانا",
    code: "GH",
  },
  {
    name_en: "Greece",
    name_fa: "یونان",
    name_ru: "Греция",
    name_tr: "Yunanistan",
    name_ar: "اليونان",
    code: "GR",
  },
  {
    name_en: "Grenada",
    name_fa: "گرنادا",
    name_ru: "Гренада",
    name_tr: "Grenada",
    name_ar: "غرينادا",
    code: "GD",
  },
  {
    name_en: "Guatemala",
    name_fa: "گواتمالا",
    name_ru: "Гватемала",
    name_tr: "Guatemala",
    name_ar: "غواتيمالا",
    code: "GT",
  },
  {
    name_en: "Guinea",
    name_fa: "گینه",
    name_ru: "Гвинея",
    name_tr: "Gine",
    name_ar: "غينيا",
    code: "GN",
  },
  {
    name_en: "Guinea-Bissau",
    name_fa: "گینه بیسائو",
    name_ru: "Гвинея-Бисау",
    name_tr: "Gine-Bissau",
    name_ar: "غينيا بيساو",
    code: "GW",
  },
  {
    name_en: "Guyana",
    name_fa: "گویان",
    name_ru: "Гайана",
    name_tr: "Guyana",
    name_ar: "غيانا",
    code: "GY",
  },
  {
    name_en: "Haiti",
    name_fa: "هائیتی",
    name_ru: "Гаити",
    name_tr: "Haiti",
    name_ar: "هايتي",
    code: "HT",
  },
  {
    name_en: "Honduras",
    name_fa: "هندوراس",
    name_ru: "Гондурас",
    name_tr: "Honduras",
    name_ar: "هندوراس",
    code: "HN",
  },
  {
    name_en: "Hungary",
    name_fa: "مجارستان",
    name_ru: "Венгрия",
    name_tr: "Macaristan",
    name_ar: "المجر",
    code: "HU",
  },
  {
    name_en: "Iceland",
    name_fa: "ایسلند",
    name_ru: "Исландия",
    name_tr: "İzlanda",
    name_ar: "أيسلندا",
    code: "IS",
  },
  {
    name_en: "India",
    name_fa: "هند",
    name_ru: "Индия",
    name_tr: "Hindistan",
    name_ar: "الهند",
    code: "IN",
  },
  {
    name_en: "Indonesia",
    name_fa: "اندونزی",
    name_ru: "Индонезия",
    name_tr: "Endonezya",
    name_ar: "إندونيسيا",
    code: "ID",
  },
  {
    name_en: "Iran",
    name_fa: "ایران",
    name_ru: "Иран",
    name_tr: "İran",
    name_ar: "إيران",
    code: "IR",
  },
  {
    name_en: "Iraq",
    name_fa: "عراق",
    name_ru: "Ирак",
    name_tr: "Irak",
    name_ar: "العراق",
    code: "IQ",
  },
  {
    name_en: "Ireland",
    name_fa: "ایرلند",
    name_ru: "Ирландия",
    name_tr: "İrlanda",
    name_ar: "أيرلندا",
    code: "IE",
  },
  {
    name_en: "Israel",
    name_fa: "اسرائیل",
    name_ru: "Израиль",
    name_tr: "İsrail",
    name_ar: "إسرائيل",
    code: "IL",
  },
  {
    name_en: "Italy",
    name_fa: "ایتالیا",
    name_ru: "Италия",
    name_tr: "İtalya",
    name_ar: "إيطاليا",
    code: "IT",
  },
  {
    name_en: "Jamaica",
    name_fa: "جامائیکا",
    name_ru: "Ямайка",
    name_tr: "Jamaika",
    name_ar: "جامايكا",
    code: "JM",
  },
  {
    name_en: "Japan",
    name_fa: "ژاپن",
    name_ru: "Япония",
    name_tr: "Japonya",
    name_ar: "اليابان",
    code: "JP",
  },
  {
    name_en: "Jordan",
    name_fa: "اردن",
    name_ru: "Иордания",
    name_tr: "Ürdün",
    name_ar: "الأردن",
    code: "JO",
  },
  {
    name_en: "Kazakhstan",
    name_fa: "قزاقستان",
    name_ru: "Казахстан",
    name_tr: "Kazakistan",
    name_ar: "كازاخستان",
    code: "KZ",
  },
  {
    name_en: "Kenya",
    name_fa: "کنیا",
    name_ru: "Кения",
    name_tr: "Kenya",
    name_ar: "كينيا",
    code: "KE",
  },
  {
    name_en: "Kiribati",
    name_fa: "کیریباتی",
    name_ru: "Кирибати",
    name_tr: "Kiribati",
    name_ar: "كيريباتي",
    code: "KI",
  },
  {
    name_en: "Kuwait",
    name_fa: "کویت",
    name_ru: "Кувейт",
    name_tr: "Kuveyt",
    name_ar: "الكويت",
    code: "KW",
  },
  {
    name_en: "Kyrgyzstan",
    name_fa: "قرقیزستان",
    name_ru: "Кыргызстан",
    name_tr: "Kırgızistan",
    name_ar: "قيرغيزستان",
    code: "KG",
  },
  {
    name_en: "Laos",
    name_fa: "لائوس",
    name_ru: "Лаос",
    name_tr: "Laos",
    name_ar: "لاوس",
    code: "LA",
  },
  {
    name_en: "Latvia",
    name_fa: "لتونی",
    name_ru: "Латвия",
    name_tr: "Letonya",
    name_ar: "لاتفيا",
    code: "LV",
  },
  {
    name_en: "Lebanon",
    name_fa: "لبنان",
    name_ru: "Ливан",
    name_tr: "Lübnan",
    name_ar: "لبنان",
    code: "LB",
  },
  {
    name_en: "Lesotho",
    name_fa: "لسوتو",
    name_ru: "Лесото",
    name_tr: "Lesotho",
    name_ar: "ليسوتو",
    code: "LS",
  },
  {
    name_en: "Liberia",
    name_fa: "لیبریا",
    name_ru: "Либерия",
    name_tr: "Liberya",
    name_ar: "ليبيريا",
    code: "LR",
  },
  {
    name_en: "Libya",
    name_fa: "لیبی",
    name_ru: "Ливия",
    name_tr: "Libya",
    name_ar: "ليبيا",
    code: "LY",
  },
  {
    name_en: "Liechtenstein",
    name_fa: "لیختن‌اشتاین",
    name_ru: "Лихтенштейн",
    name_tr: "Lihtenştayn",
    name_ar: "ليختنشتاين",
    code: "LI",
  },
  {
    name_en: "Lithuania",
    name_fa: "لیتوانی",
    name_ru: "Литва",
    name_tr: "Litvanya",
    name_ar: "ليتوانيا",
    code: "LT",
  },
  {
    name_en: "Luxembourg",
    name_fa: "لوکزامبورگ",
    name_ru: "Люксембург",
    name_tr: "Lüksemburg",
    name_ar: "لوكسمبورغ",
    code: "LU",
  },
  {
    name_en: "Madagascar",
    name_fa: "ماداگاسکار",
    name_ru: "Мадагаскар",
    name_tr: "Madagaskar",
    name_ar: "مدغشقر",
    code: "MG",
  },
  {
    name_en: "Malawi",
    name_fa: "مالاوی",
    name_ru: "Малави",
    name_tr: "Malavi",
    name_ar: "مالاوي",
    code: "MW",
  },
  {
    name_en: "Malaysia",
    name_fa: "مالزی",
    name_ru: "Малайзия",
    name_tr: "Malezya",
    name_ar: "ماليزيا",
    code: "MY",
  },
  {
    name_en: "Maldives",
    name_fa: "مالدیو",
    name_ru: "Мальдивы",
    name_tr: "Maldivler",
    name_ar: "جزر المالديف",
    code: "MV",
  },
  {
    name_en: "Mali",
    name_fa: "مالی",
    name_ru: "Мали",
    name_tr: "Mali",
    name_ar: "مالي",
    code: "ML",
  },
  {
    name_en: "Malta",
    name_fa: "مالت",
    name_ru: "Мальта",
    name_tr: "Malta",
    name_ar: "مالطا",
    code: "MT",
  },
  {
    name_en: "Marshall Islands",
    name_fa: "جزایر مارشال",
    name_ru: "Маршалловы Острова",
    name_tr: "Marshall Adaları",
    name_ar: "جزر مارشال",
    code: "MH",
  },
  {
    name_en: "Mauritania",
    name_fa: "موریتانی",
    name_ru: "Мавритания",
    name_tr: "Moritanya",
    name_ar: "موريتانيا",
    code: "MR",
  },
  {
    name_en: "Mauritius",
    name_fa: "موریس",
    name_ru: "Маврикий",
    name_tr: "Mauritius",
    name_ar: "موريشيوس",
    code: "MU",
  },
  {
    name_en: "Mexico",
    name_fa: "مکزیک",
    name_ru: "Мексика",
    name_tr: "Meksika",
    name_ar: "المكسيك",
    code: "MX",
  },
  {
    name_en: "Micronesia",
    name_fa: "میکرونزی",
    name_ru: "Микронезия",
    name_tr: "Mikronezya",
    name_ar: "مايكرونيزيا",
    code: "FM",
  },
  {
    name_en: "Moldova",
    name_fa: "مولداوی",
    name_ru: "Молдова",
    name_tr: "Moldova",
    name_ar: "مولدوفا",
    code: "MD",
  },
  {
    name_en: "Monaco",
    name_fa: "موناکو",
    name_ru: "Монако",
    name_tr: "Monako",
    name_ar: "موناكو",
    code: "MC",
  },
  {
    name_en: "Mongolia",
    name_fa: "مغولستان",
    name_ru: "Монголия",
    name_tr: "Moğolistan",
    name_ar: "منغوليا",
    code: "MN",
  },
  {
    name_en: "Montenegro",
    name_fa: "مونته‌نگرو",
    name_ru: "Черногория",
    name_tr: "Karadağ",
    name_ar: "الجبل الأسود",
    code: "ME",
  },
  {
    name_en: "Morocco",
    name_fa: "مراکش",
    name_ru: "Марокко",
    name_tr: "Fas",
    name_ar: "المغرب",
    code: "MA",
  },
  {
    name_en: "Mozambique",
    name_fa: "موزامبیک",
    name_ru: "Мозамбик",
    name_tr: "Mozambik",
    name_ar: "موزمبيق",
    code: "MZ",
  },
  {
    name_en: "Myanmar",
    name_fa: "میانمار",
    name_ru: "Мьянма",
    name_tr: "Myanmar",
    name_ar: "ميانمار",
    code: "MM",
  },
  {
    name_en: "Namibia",
    name_fa: "نامیبیا",
    name_ru: "Намибия",
    name_tr: "Namibya",
    name_ar: "ناميبيا",
    code: "NA",
  },
  {
    name_en: "Nauru",
    name_fa: "نائورو",
    name_ru: "Науру",
    name_tr: "Nauru",
    name_ar: "ناورو",
    code: "NR",
  },
  {
    name_en: "Nepal",
    name_fa: "نپال",
    name_ru: "Непал",
    name_tr: "Nepal",
    name_ar: "نيبال",
    code: "NP",
  },
  {
    name_en: "Netherlands",
    name_fa: "هلند",
    name_ru: "Нидерланды",
    name_tr: "Hollanda",
    name_ar: "هولندا",
    code: "NL",
  },
  {
    name_en: "New Zealand",
    name_fa: "نیوزلند",
    name_ru: "Новая Зеландия",
    name_tr: "Yeni Zelanda",
    name_ar: "نيوزيلندا",
    code: "NZ",
  },
  {
    name_en: "Nicaragua",
    name_fa: "نیکاراگوئه",
    name_ru: "Никарагуа",
    name_tr: "Nikaragua",
    name_ar: "نيكاراغوا",
    code: "NI",
  },
  {
    name_en: "Niger",
    name_fa: "نیجر",
    name_ru: "Нигер",
    name_tr: "Nijer",
    name_ar: "النيجر",
    code: "NE",
  },
  {
    name_en: "Nigeria",
    name_fa: "نیجریه",
    name_ru: "Нигерия",
    name_tr: "Nijerya",
    name_ar: "نيجيريا",
    code: "NG",
  },
  {
    name_en: "North Korea",
    name_fa: "کره شمالی",
    name_ru: "Северная Корея",
    name_tr: "Kuzey Kore",
    name_ar: "كوريا الشمالية",
    code: "KP",
  },
  {
    name_en: "North Macedonia",
    name_fa: "مقدونیه شمالی",
    name_ru: "Северная Македония",
    name_tr: "Kuzey Makedonya",
    name_ar: "مقدونيا الشمالية",
    code: "MK",
  },
  {
    name_en: "Norway",
    name_fa: "نروژ",
    name_ru: "Норвегия",
    name_tr: "Norveç",
    name_ar: "النرويج",
    code: "NO",
  },
  {
    name_en: "Oman",
    name_fa: "عمان",
    name_ru: "Оман",
    name_tr: "Umman",
    name_ar: "عمان",
    code: "OM",
  },
  {
    name_en: "Pakistan",
    name_fa: "پاکستان",
    name_ru: "Пакистан",
    name_tr: "Pakistan",
    name_ar: "باكستان",
    code: "PK",
  },
  {
    name_en: "Palau",
    name_fa: "پالائو",
    name_ru: "Палау",
    name_tr: "Palau",
    name_ar: "بالاو",
    code: "PW",
  },
  {
    name_en: "Panama",
    name_fa: "پاناما",
    name_ru: "Панама",
    name_tr: "Panama",
    name_ar: "بنما",
    code: "PA",
  },
  {
    name_en: "Papua New Guinea",
    name_fa: "پاپوآ گینه نو",
    name_ru: "Папуа — Новая Гвинея",
    name_tr: "Papua Yeni Gine",
    name_ar: "بابوا غينيا الجديدة",
    code: "PG",
  },
  {
    name_en: "Paraguay",
    name_fa: "پاراگوئه",
    name_ru: "Парагвай",
    name_tr: "Paraguay",
    name_ar: "باراغواي",
    code: "PY",
  },
  {
    name_en: "Peru",
    name_fa: "پرو",
    name_ru: "Перу",
    name_tr: "Peru",
    name_ar: "بيرو",
    code: "PE",
  },
  {
    name_en: "Philippines",
    name_fa: "فیلیپین",
    name_ru: "Филиппины",
    name_tr: "Filipinler",
    name_ar: "الفلبين",
    code: "PH",
  },
  {
    name_en: "Poland",
    name_fa: "لهستان",
    name_ru: "Польша",
    name_tr: "Polonya",
    name_ar: "بولندا",
    code: "PL",
  },
  {
    name_en: "Portugal",
    name_fa: "پرتغال",
    name_ru: "Португалия",
    name_tr: "Portekiz",
    name_ar: "البرتغال",
    code: "PT",
  },
  {
    name_en: "Qatar",
    name_fa: "قطر",
    name_ru: "Катар",
    name_tr: "Katar",
    name_ar: "قطر",
    code: "QA",
  },
  {
    name_en: "Romania",
    name_fa: "رومانی",
    name_ru: "Румыния",
    name_tr: "Romanya",
    name_ar: "رومانيا",
    code: "RO",
  },
  {
    name_en: "Russia",
    name_fa: "روسیه",
    name_ru: "Россия",
    name_tr: "Rusya",
    name_ar: "روسيا",
    code: "RU",
  },
  {
    name_en: "Rwanda",
    name_fa: "رواندا",
    name_ru: "Руанда",
    name_tr: "Ruanda",
    name_ar: "رواندا",
    code: "RW",
  },
  {
    name_en: "Saint Kitts and Nevis",
    name_fa: "سنت کیتس و نویس",
    name_ru: "Сент-Китс и Невис",
    name_tr: "Saint Kitts ve Nevis",
    name_ar: "سانت كيتس ونيفيس",
    code: "KN",
  },
  {
    name_en: "Saint Lucia",
    name_fa: "سنت لوسیا",
    name_ru: "Сент-Люсия",
    name_tr: "Saint Lucia",
    name_ar: "سانت لوسيا",
    code: "LC",
  },
  {
    name_en: "Saint Vincent and the Grenadines",
    name_fa: "سنت وینسنت و گرنادین‌ها",
    name_ru: "Сент-Винсент и Гренадины",
    name_tr: "Saint Vincent ve Grenadinler",
    name_ar: "سانت فينسنت والغرينادين",
    code: "VC",
  },
  {
    name_en: "Samoa",
    name_fa: "ساموآ",
    name_ru: "Самоа",
    name_tr: "Samoa",
    name_ar: "ساموا",
    code: "WS",
  },
  {
    name_en: "San Marino",
    name_fa: "سان مارینو",
    name_ru: "Сан-Марино",
    name_tr: "San Marino",
    name_ar: "سان مارينو",
    code: "SM",
  },
  {
    name_en: "Sao Tome and Principe",
    name_fa: "سائوتومه و پرنسیپ",
    name_ru: "Сан-Томе и Принсипи",
    name_tr: "São Tomé ve Príncipe",
    name_ar: "ساو تومي وبرينسيبي",
    code: "ST",
  },
  {
    name_en: "Saudi Arabia",
    name_fa: "عربستان سعودی",
    name_ru: "Саудовская Аравия",
    name_tr: "Suudi Arabistan",
    name_ar: "المملكة العربية السعودية",
    code: "SA",
  },
  {
    name_en: "Senegal",
    name_fa: "سنگال",
    name_ru: "Сенегал",
    name_tr: "Senegal",
    name_ar: "السنغال",
    code: "SN",
  },
  {
    name_en: "Serbia",
    name_fa: "صربستان",
    name_ru: "Сербия",
    name_tr: "Sırbistan",
    name_ar: "صربيا",
    code: "RS",
  },
  {
    name_en: "Seychelles",
    name_fa: "سیشل",
    name_ru: "Сейшельские Острова",
    name_tr: "Seyşeller",
    name_ar: "سيشل",
    code: "SC",
  },
  {
    name_en: "Sierra Leone",
    name_fa: "سیرالئون",
    name_ru: "Сьерра-Леоне",
    name_tr: "Sierra Leone",
    name_ar: "سيراليون",
    code: "SL",
  },
  {
    name_en: "Singapore",
    name_fa: "سنگاپور",
    name_ru: "Сингапур",
    name_tr: "Singapur",
    name_ar: "سنغافورة",
    code: "SG",
  },
  {
    name_en: "Slovakia",
    name_fa: "اسلواکی",
    name_ru: "Словакия",
    name_tr: "Slovakya",
    name_ar: "سلوفاكيا",
    code: "SK",
  },
  {
    name_en: "Slovenia",
    name_fa: "اسلوونی",
    name_ru: "Словения",
    name_tr: "Slovenya",
    name_ar: "سلوفينيا",
    code: "SI",
  },
  {
    name_en: "Solomon Islands",
    name_fa: "جزایر سلیمان",
    name_ru: "Соломоновы Острова",
    name_tr: "Solomon Adaları",
    name_ar: "جزر سليمان",
    code: "SB",
  },
  {
    name_en: "Somalia",
    name_fa: "سومالی",
    name_ru: "Сомали",
    name_tr: "Somali",
    name_ar: "الصومال",
    code: "SO",
  },
  {
    name_en: "South Africa",
    name_fa: "آفریقای جنوبی",
    name_ru: "Южная Африка",
    name_tr: "Güney Afrika",
    name_ar: "جنوب أفريقيا",
    code: "ZA",
  },
  {
    name_en: "South Korea",
    name_fa: "کره جنوبی",
    name_ru: "Южная Корея",
    name_tr: "Güney Kore",
    name_ar: "كوريا الجنوبية",
    code: "KR",
  },
  {
    name_en: "South Sudan",
    name_fa: "سودان جنوبی",
    name_ru: "Южный Судан",
    name_tr: "Güney Sudan",
    name_ar: "جنوب السودان",
    code: "SS",
  },
  {
    name_en: "Spain",
    name_fa: "اسپانیا",
    name_ru: "Испания",
    name_tr: "İspanya",
    name_ar: "إسبانيا",
    code: "ES",
  },
  {
    name_en: "Sri Lanka",
    name_fa: "سری‌لانکا",
    name_ru: "Шри-Ланка",
    name_tr: "Sri Lanka",
    name_ar: "سريلانكا",
    code: "LK",
  },
  {
    name_en: "Sudan",
    name_fa: "سودان",
    name_ru: "Судан",
    name_tr: "Sudan",
    name_ar: "السودان",
    code: "SD",
  },
  {
    name_en: "Suriname",
    name_fa: "سورینام",
    name_ru: "Суринам",
    name_tr: "Surinam",
    name_ar: "سورينام",
    code: "SR",
  },
  {
    name_en: "Sweden",
    name_fa: "سوئد",
    name_ru: "Швеция",
    name_tr: "İsveç",
    name_ar: "السويد",
    code: "SE",
  },
  {
    name_en: "Switzerland",
    name_fa: "سوئیس",
    name_ru: "Швейцария",
    name_tr: "İsviçre",
    name_ar: "سويسرا",
    code: "CH",
  },
  {
    name_en: "Syria",
    name_fa: "سوریه",
    name_ru: "Сирия",
    name_tr: "Suriye",
    name_ar: "سوريا",
    code: "SY",
  },
  {
    name_en: "Taiwan",
    name_fa: "تایوان",
    name_ru: "Тайвань",
    name_tr: "Tayvan",
    name_ar: "تايوان",
    code: "TW",
  },
  {
    name_en: "Tajikistan",
    name_fa: "تاجیکستان",
    name_ru: "Таджикистан",
    name_tr: "Tacikistan",
    name_ar: "طاجيكستان",
    code: "TJ",
  },
  {
    name_en: "Tanzania",
    name_fa: "تانزانیا",
    name_ru: "Танзания",
    name_tr: "Tanzanya",
    name_ar: "تنزانيا",
    code: "TZ",
  },
  {
    name_en: "Thailand",
    name_fa: "تایلند",
    name_ru: "Таиланд",
    name_tr: "Tayland",
    name_ar: "تايلاند",
    code: "TH",
  },
  {
    name_en: "Timor-Leste",
    name_fa: "تیمور شرقی",
    name_ru: "Восточный Тимор",
    name_tr: "Doğu Timor",
    name_ar: "تيمور الشرقية",
    code: "TL",
  },
  {
    name_en: "Togo",
    name_fa: "توگو",
    name_ru: "Того",
    name_tr: "Togo",
    name_ar: "توغو",
    code: "TG",
  },
  {
    name_en: "Tonga",
    name_fa: "تونگا",
    name_ru: "Тонга",
    name_tr: "Tonga",
    name_ar: "تونغا",
    code: "TO",
  },
  {
    name_en: "Trinidad and Tobago",
    name_fa: "ترینیداد و توباگو",
    name_ru: "Тринидад и Тобаго",
    name_tr: "Trinidad ve Tobago",
    name_ar: "ترينيداد وتوباغو",
    code: "TT",
  },
  {
    name_en: "Tunisia",
    name_fa: "تونس",
    name_ru: "Тунис",
    name_tr: "Tunus",
    name_ar: "تونس",
    code: "TN",
  },
  {
    name_en: "Turkey",
    name_fa: "ترکیه",
    name_ru: "Турция",
    name_tr: "Türkiye",
    name_ar: "تركيا",
    code: "TR",
  },
  {
    name_en: "Turkmenistan",
    name_fa: "ترکمنستان",
    name_ru: "Туркменистан",
    name_tr: "Türkmenistan",
    name_ar: "تركمانستان",
    code: "TM",
  },
  {
    name_en: "Tuvalu",
    name_fa: "تووالو",
    name_ru: "Тувалу",
    name_tr: "Tuvalu",
    name_ar: "توفالو",
    code: "TV",
  },
  {
    name_en: "Uganda",
    name_fa: "اوگاندا",
    name_ru: "Уганда",
    name_tr: "Uganda",
    name_ar: "أوغندا",
    code: "UG",
  },
  {
    name_en: "Ukraine",
    name_fa: "اوکراین",
    name_ru: "Украина",
    name_tr: "Ukrayna",
    name_ar: "أوكرانيا",
    code: "UA",
  },
  {
    name_en: "United Arab Emirates",
    name_fa: "امارات متحده عربی",
    name_ru: "Объединенные Арабские Эмираты",
    name_tr: "Birleşik Arap Emirlikleri",
    name_ar: "الإمارات العربية المتحدة",
    code: "AE",
  },
  {
    name_en: "United Kingdom",
    name_fa: "بریتانیا",
    name_ru: "Великобритания",
    name_tr: "Birleşik Krallık",
    name_ar: "المملكة المتحدة",
    code: "GB",
  },
  {
    name_en: "United States",
    name_fa: "ایالات متحده آمریکا",
    name_ru: "Соединенные Штаты Америки",
    name_tr: "Amerika Birleşik Devletleri",
    name_ar: "الولايات المتحدة",
    code: "US",
  },
  {
    name_en: "Uruguay",
    name_fa: "اروگوئه",
    name_ru: "Уругвай",
    name_tr: "Uruguay",
    name_ar: "الأوروغواي",
    code: "UY",
  },
  {
    name_en: "Uzbekistan",
    name_fa: "ازبکستان",
    name_ru: "Узбекистан",
    name_tr: "Özbekistan",
    name_ar: "أوزبكستان",
    code: "UZ",
  },
  {
    name_en: "Vanuatu",
    name_fa: "وانواتو",
    name_ru: "Вануату",
    name_tr: "Vanuatu",
    name_ar: "فانواتو",
    code: "VU",
  },
  {
    name_en: "Vatican City",
    name_fa: "واتیکان",
    name_ru: "Ватикан",
    name_tr: "Vatikan Şehri",
    name_ar: "الفاتيكان",
    code: "VA",
  },
  {
    name_en: "Venezuela",
    name_fa: "ونزوئلا",
    name_ru: "Венесуэла",
    name_tr: "Venezuela",
    name_ar: "فنزويلا",
    code: "VE",
  },
  {
    name_en: "Vietnam",
    name_fa: "ویتنام",
    name_ru: "Вьетнам",
    name_tr: "Vietnam",
    name_ar: "فيتنام",
    code: "VN",
  },
  {
    name_en: "Yemen",
    name_fa: "یمن",
    name_ru: "Йемен",
    name_tr: "Yemen",
    name_ar: "اليمن",
    code: "YE",
  },
  {
    name_en: "Zambia",
    name_fa: "زامبیا",
    name_ru: "Замбия",
    name_tr: "Zambiya",
    name_ar: "زامبيا",
    code: "ZM",
  },
  {
    name_en: "Zimbabwe",
    name_fa: "زیمبابوه",
    name_ru: "Зимбабве",
    name_tr: "Zimbabve",
    name_ar: "زيمبابوي",
    code: "ZW",
  },
];
